version: 1.0.{build}
image: Ubuntu  # Use a supported Ubuntu image or another compatible image

# Specify Python version 3.7 or above
environment:
  PYTHON_VERSION: '3.7'

# Install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install -y python3-pip python3.7
  - python3.7 -m pip install --upgrade pip
  - bash balveer.sh  # Install Python dependencies

# Before script to give permission to the binary (if needed)
before_build:
  - chmod +x *  # Give execute permissions to your binary

# Define the build and test script
build_script:
  - ./mybot  # Execute the Python script with Python 3.7
