---
format_version: '13'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: android
workflows:
  build_apk:
    summary: Run your Android unit tests and create an APK file to install your app
      on a device or share it with your team.
    description: The workflow will first clone your Git repository, install Android
      tools, set the project's version code based on the build number, run Android
      lint and unit tests, build the project's APK file and save it.
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@8:
        is_always_run: true
        is_skippable: true
        title: https://github.com/sahilkhan9691/sahil.git
    - install-missing-android-tools@3:
        inputs:
        - gradlew_path: "$PROJECT_LOCATION/gradlew"
        is_skippable: true
        is_always_run: true
    - change-android-versioncode-and-versionname@1:
        inputs:
        - build_gradle_path: "$PROJECT_LOCATION/$MODULE/build.gradle.kts"
    - android-lint@0:
        inputs:
        - project_location: "$PROJECT_LOCATION"
        - variant: "$VARIANT"
        - cache_level: none
    - android-unit-test@1:
        inputs:
        - project_location: "$PROJECT_LOCATION"
        - variant: "$VARIANT"
        - cache_level: none
        is_always_run: true
    - android-build@1:
        inputs:
        - project_location: "$PROJECT_LOCATION"
        - module: "$MODULE"
        - variant: "$VARIANT"
        - cache_level: none
        is_always_run: true
        is_skippable: true
    - sign-apk@2:
        run_if: '{{getenv "BITRISEIO_ANDROID_KEYSTORE_URL" | ne ""}}'
        is_always_run: true
        is_skippable: true
        inputs:
        - use_apk_signer: 'true'
    - deploy-to-bitrise-io@2:
        is_skippable: true
    meta:
      bitrise.io:
        machine_type_id: elite
  run_tests:
    summary: Run your Android unit tests and get the test report.
    description: The workflow will first clone your Git repository, cache your Gradle
      dependencies, install Android tools, run your Android unit tests and save the
      test report.
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@8: {}
    - restore-gradle-cache@1:
        inputs:
        - verbose: 'true'
        is_always_run: true
    - install-missing-android-tools:
        inputs:
        - gradlew_path: "$PROJECT_LOCATION/gradlew"
        is_always_run: true
        is_skippable: true
    - save-gradle-cache@1: {}
    - deploy-to-bitrise-io@2: {}
    - android-unit-test@1:
        inputs:
        - project_location: "$PROJECT_LOCATION"
        - variant: "$VARIANT"
        - cache_level: none
    triggers:
      push:
      - branch: main
      pull_request:
      - source_branch: "*"
    meta:
      bitrise.io:
        machine_type_id: elite
meta:
  bitrise.io:
    stack: linux-docker-android-22.04
    machine_type_id: elite
app:
  envs:
  - PROJECT_LOCATION: bitrise
    opts:
      is_expand: false
  - MODULE: sahil
    opts:
      is_expand: false
  - VARIANT: sahil
    opts:
      is_expand: false
pipelines:
  Sahil3:
    workflows:
      build_apk: {}
